### PR TITLE
[Review] Updated OneByteAtAAtime

### PR DESCRIPTION
**Pull request by wafaajaunnoo**

### CODE REVIEW

**Comment by houzyk** [comment]
In Review

**Comment by houzyk** [comment]
LGTM. This version improves on the last one by being more systematic in its writing. You guide the reader on what you want to do, especially at the beginning. This is the 101 thing for a good Philosophy paper.

Thanks for the PR.

**Comment by wafaajaunnoo** [comment]
----------------------------------------------------
This is an automated e-mail


Hi!

Please note that I am currently taking a break from social media.  As a
result, I may not be able to respond promptly to any messages sent to my
email address.  For any *urgent* matters, please reach out to me directly
on +230 5803 7784.

I apologise for any inconvenience caused and appreciate your understanding.

Regards,
--
Jaunnoo Wafaa Al'Uzayma
Application Development Associate, Accenture

+230 5803 7784 <+230+5803+7784>  |  ***@***.***

Mosque Road, Chemin Grenier, Mauritius
<https://maps.google.com/?q=Mosque+Road,+Chemin+Grenier,+Mauritius>
[image: linkedin]
<https://www.linkedin.com/in/wafaa-al-uzayma-jaunnoo-ab2844203/>

**Comment by wafaajaunnoo** [comment]
Thank **you**!

**Pull request merged**
